"""empty message

Revision ID: 2fa24a6424fd
Revises: 
Create Date: 2025-05-16 15:58:23.702857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa24a6424fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users__clinics')
    op.add_column('users', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'clinics', ['clinic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'clinic_id')
    op.create_table('users__clinics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name='users__clinics_clinic_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users__clinics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users__clinics_pkey')
    )
    # ### end Alembic commands ###
