"""empty message

Revision ID: 75d57b5f80b7
Revises: 2fa24a6424fd
Create Date: 2025-05-18 13:02:34.483212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d57b5f80b7'
down_revision: Union[str, None] = '2fa24a6424fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('clinic_city_title_unique_idx', 'clinics', ['city_id', 'title'], unique=True, postgresql_using='btree')
    op.create_index('clinic_email_unique_idx', 'clinics', ['email'], unique=True, postgresql_using='btree')
    op.create_index('clinic_phone_unique_idx', 'clinics', ['phone'], unique=True, postgresql_using='btree')
    op.create_index('donor_pet_date_status_idx', 'donors', ['pet_id', 'donation_date', 'donor_status_id'], unique=False, postgresql_using='btree')
    op.create_index('donor_pet_recipient_unique_idx', 'donors', ['pet_id', 'recipient_id', 'donation_date'], unique=True, postgresql_using='btree')
    op.create_index(op.f('ix_donors_donation_date'), 'donors', ['donation_date'], unique=False)
    op.create_index('pet_user_name_unique_idx', 'pets', ['user_id', 'name'], unique=True, postgresql_using='btree')
    op.create_index('recipient_pet_blood_component_unique_idx', 'recipients', ['pet_id', 'blood_component_id'], unique=True, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recipient_pet_blood_component_unique_idx', table_name='recipients', postgresql_using='btree')
    op.drop_index('pet_user_name_unique_idx', table_name='pets', postgresql_using='btree')
    op.drop_index(op.f('ix_donors_donation_date'), table_name='donors')
    op.drop_index('donor_pet_recipient_unique_idx', table_name='donors', postgresql_using='btree')
    op.drop_index('donor_pet_date_status_idx', table_name='donors', postgresql_using='btree')
    op.drop_index('clinic_phone_unique_idx', table_name='clinics', postgresql_using='btree')
    op.drop_index('clinic_email_unique_idx', table_name='clinics', postgresql_using='btree')
    op.drop_index('clinic_city_title_unique_idx', table_name='clinics', postgresql_using='btree')
    # ### end Alembic commands ###
